server:
  port: 8703


spring:
  application:
    name: marcet-front

# http://localhost:8703/?#!/
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}