server:
  port: 8704
  servlet:
    context-path:

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/market_fp_db?serverTimezone=GMT
#    username: root
#    password: Zz123456

    url: jdbc:mysql://109.173.124.43:43306/market_fp_db?serverTimezone=GMT
    username: ${DB_USR}
    password: ${DB_PWD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name: marcet-service


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  file: logs/log_file.log
